import Groq from 'groq-sdk'

const groq = new Groq({
  apiKey: import.meta.env.VITE_GROQ_API_KEY,
})

export const groqService = {
  /**
   * Generate tailored resume content using Groq API
   * @param {Object} personalData - User's personal information
   * @param {Object} jobData - Job application details
   * @returns {Promise<Object>} Generated resume content
   */
  generateResumeContent: async (personalData, jobData) => {
    try {
      if (!import.meta.env.VITE_GROQ_API_KEY) {
        throw new Error('Groq API key is not configured. Please add VITE_GROQ_API_KEY to your .env file.')
      }

      const prompt = createPrompt(personalData, jobData)

      const completion = await groq.chat.completions.create({
        messages: [
          {
            role: 'system',
            content: `You are an expert resume writer and career counselor. Your task is to create a professional, tailored resume that highlights the candidate's experience and skills relevant to the job they're applying for. Focus on:
1. Creating a compelling professional summary
2. Rewriting work experience descriptions to match job requirements
3. Highlighting relevant skills and achievements
4. Using industry-standard keywords
5. Quantifying achievements where possible
6. Making the resume ATS-friendly

Return the response as a JSON object with the following structure:
{
  "summary": "tailored professional summary",
  "workExperience": [
    {
      "company": "company name",
      "position": "position title",
      "startDate": "start date",
      "endDate": "end date or 'Present'",
      "responsibilities": "tailored responsibilities and achievements"
    }
  ],
  "skills": ["relevant skill 1", "relevant skill 2", ...]
}`,
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        model: 'llama-3.1-70b-versatile',
        temperature: 0.7,
        max_tokens: 2000,
      })

      const content = completion.choices[0]?.message?.content || ''
      
      // Try to parse JSON from the response
      let generatedContent
      try {
        // Extract JSON from markdown code blocks if present
        const jsonMatch = content.match(/```json\n([\s\S]*?)\n```/) || content.match(/```\n([\s\S]*?)\n```/)
        const jsonString = jsonMatch ? jsonMatch[1] : content
        generatedContent = JSON.parse(jsonString)
      } catch (parseError) {
        // If JSON parsing fails, create a fallback structure
        console.warn('Failed to parse AI response as JSON, using fallback:', parseError)
        generatedContent = {
          summary: content.split('\n')[0] || 'Professional summary generated by AI',
          workExperience: personalData.workExperience || [],
          skills: personalData.skills || [],
        }
      }

      return {
        success: true,
        data: generatedContent,
      }
    } catch (error) {
      console.error('Error generating resume content:', error)
      return {
        success: false,
        error: error.message || 'Failed to generate resume content',
      }
    }
  },

  /**
   * Generate only the professional summary
   */
  generateSummary: async (personalData, jobData) => {
    try {
      const prompt = `Create a compelling professional summary (2-3 sentences) for a resume based on:
      
Personal Information:
- Name: ${personalData.name || 'Candidate'}
- Experience: ${personalData.workExperience?.length || 0} position(s)
- Skills: ${personalData.skills?.join(', ') || 'Various skills'}

Job Application:
- Title: ${jobData.jobTitle || 'Position'}
- Description: ${jobData.jobDescription?.substring(0, 500) || 'Not provided'}

Make it concise, impactful, and tailored to the job requirements.`

      const completion = await groq.chat.completions.create({
        messages: [
          {
            role: 'system',
            content: 'You are an expert resume writer. Create professional, concise summaries.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        model: 'llama-3.1-70b-versatile',
        temperature: 0.7,
        max_tokens: 200,
      })

      return {
        success: true,
        summary: completion.choices[0]?.message?.content || '',
      }
    } catch (error) {
      console.error('Error generating summary:', error)
      return {
        success: false,
        error: error.message || 'Failed to generate summary',
      }
    }
  },
}

/**
 * Create a comprehensive prompt for resume generation
 */
function createPrompt(personalData, jobData) {
  return `Create a tailored resume for the following candidate applying to this position:

CANDIDATE INFORMATION:
Name: ${personalData.name || 'Not provided'}
Email: ${personalData.email || 'Not provided'}
Phone: ${personalData.phone || 'Not provided'}

Professional Summary:
${personalData.summary || 'No summary provided'}

Work Experience:
${formatWorkExperience(personalData.workExperience)}

Education:
${formatEducation(personalData.education)}

Skills: ${personalData.skills?.join(', ') || 'Not provided'}

Certifications:
${formatCertifications(personalData.certifications)}

Languages: ${formatLanguages(personalData.languages)}

JOB APPLICATION:
Job Title: ${jobData.jobTitle || 'Not specified'}

Job Description:
${jobData.jobDescription || 'No job description provided'}

INSTRUCTIONS:
1. Create an optimized professional summary (2-3 sentences) that highlights relevant experience for this specific job
2. Rewrite each work experience entry to emphasize achievements and responsibilities that match the job requirements
3. Use action verbs and quantify achievements where possible
4. Highlight skills that are most relevant to the job
5. Use keywords from the job description naturally
6. Make the resume ATS-friendly and professional
7. Ensure all dates and company names are preserved exactly as provided

Return ONLY a valid JSON object with the structure specified in the system message.`
}

function formatWorkExperience(experiences) {
  if (!experiences || experiences.length === 0) {
    return 'No work experience provided'
  }
  return experiences
    .map(
      (exp, index) => `
${index + 1}. ${exp.position || 'Position'} at ${exp.company || 'Company'}
   Period: ${exp.startDate || 'Start'} - ${exp.current ? 'Present' : exp.endDate || 'End'}
   Responsibilities: ${exp.responsibilities || 'Not provided'}`
    )
    .join('\n')
}

function formatEducation(education) {
  if (!education || education.length === 0) {
    return 'No education provided'
  }
  return education
    .map(
      (edu, index) => `
${index + 1}. ${edu.degree || 'Degree'} in ${edu.field || 'Field'} from ${edu.institution || 'Institution'}
   Period: ${edu.startDate || 'Start'} - ${edu.current ? 'Present' : edu.endDate || 'End'}`
    )
    .join('\n')
}

function formatCertifications(certifications) {
  if (!certifications || certifications.length === 0) {
    return 'No certifications provided'
  }
  return certifications
    .map((cert) => `- ${cert.name || 'Certification'} from ${cert.issuer || 'Issuer'} (${cert.date || 'Date'})`)
    .join('\n')
}

function formatLanguages(languages) {
  if (!languages || languages.length === 0) {
    return 'No languages provided'
  }
  return languages.map((lang) => `${lang.name || 'Language'} (${lang.proficiency || 'Proficiency'})`).join(', ')
}

